[package]
name = "rusty_dupe_scan"
version = "0.1.0"
authors = ["Faark <bbdev@faark.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.8.0"